import 'package:flutter/material.dart';

List<String> creditTypes = ['Kartu Kredit', 'Pay Later'];
List<String> priorityTypes = ['Rendah', 'Sedang', 'Tinggi'];
List<String> transactionTypes = ['Uang Keluar', 'Uang Masuk', 'Transfer'];
List<String> timeUnits = ['hari', 'minggu', 'bulan', 'tahun'];

List<String> colors = [
  'cc041b',
  'e05f09',
  'f5c400',
  '66e60b',
  '04bf36',
  '12e6d0',
  '0da9d4',
  '0f667b',
  '0a19c2',
  '7305e8',
  'd61bf2',
  'f551b0',
];

Map<String, IconData> icons = {
  'account_balance_wallet_outlined': Icons.account_balance_wallet_outlined,
  'restaurant_rounded': Icons.restaurant_rounded,
  'egg_alt_outlined': Icons.egg_alt_outlined,
  'fastfood_outlined': Icons.fastfood_outlined,
  'bakery_dining_outlined': Icons.bakery_dining_outlined,
  'airport_shuttle_outlined': Icons.airport_shuttle_outlined,
  'two_wheeler_rounded': Icons.two_wheeler_rounded,
  'directions_car_outlined': Icons.directions_car_outlined,
  'directions_bus_outlined': Icons.directions_bus_outlined,
  'directions_subway_outlined': Icons.directions_subway_outlined,
  'directions_ferry_outlined': Icons.directions_ferry_outlined,
  'airplanemode_on_rounded': Icons.airplanemode_on_rounded,
  'attractions_outlined': Icons.attractions_outlined,
  'videogame_asset_outlined': Icons.videogame_asset_outlined,
  'movie_creation_outlined': Icons.movie_creation_outlined,
  'local_florist_outlined': Icons.local_florist_outlined,
  'volunteer_activism_outlined': Icons.volunteer_activism_outlined,
  'favorite_outline_rounded': Icons.favorite_outline_rounded,
  'person_remove_outlined': Icons.person_remove_outlined,
  'receipt_long_rounded': Icons.receipt_long_rounded,
  'bolt_rounded': Icons.bolt_rounded,
  'water_drop_outlined': Icons.water_drop_outlined,
  'wifi_rounded': Icons.wifi_rounded,
  'house_outlined': Icons.house_outlined,
  'child_friendly_outlined': Icons.child_friendly_outlined,
  'pets_rounded': Icons.pets_rounded,
  'weekend_outlined': Icons.weekend_outlined,
  'self_improvement_rounded': Icons.self_improvement_rounded,
  'vaccines_outlined': Icons.vaccines_outlined,
  'fitness_center_rounded': Icons.fitness_center_rounded,
  'spa_outlined': Icons.spa_outlined,
  'local_mall_outlined': Icons.local_mall_outlined,
  'dry_cleaning_outlined': Icons.dry_cleaning_outlined,
  'devices_rounded': Icons.devices_rounded,
  'beach_access_outlined': Icons.beach_access_outlined,
  'school_outlined': Icons.school_outlined,
  'work_outline': Icons.work_outline,
  'attach_money_rounded': Icons.attach_money_rounded,
  'card_giftcard_rounded': Icons.card_giftcard_rounded,
  'elderly_rounded': Icons.elderly_rounded,
  'ssid_chart_rounded': Icons.ssid_chart_rounded,
  'store_outlined': Icons.store_outlined,
  'ac_unit_rounded': Icons.ac_unit_rounded,
  'abc_rounded': Icons.abc_rounded,
  'access_alarm_rounded': Icons.access_alarm_rounded,
  'accessibility_new_rounded': Icons.accessibility_new_rounded,
  'accessible_forward_rounded': Icons.accessible_forward_rounded,
  'accessible_rounded': Icons.accessible_rounded,
  'adf_scanner_outlined': Icons.adf_scanner_outlined,
  'adjust_rounded': Icons.adjust_rounded,
  'adobe_rounded': Icons.adobe_rounded,
  'agriculture_outlined': Icons.agriculture_outlined,
  'air_rounded': Icons.air_rounded,
  'airline_seat_flat_outlined': Icons.airline_seat_flat_outlined,
  'airline_seat_flat_angled_outlined': Icons.airline_seat_flat_angled_outlined,
  'airline_seat_individual_suite_outlined': Icons.airline_seat_individual_suite_outlined,
  'airline_seat_recline_extra_rounded': Icons.airline_seat_recline_extra_rounded,
  'airline_seat_recline_normal_rounded': Icons.airline_seat_recline_normal_rounded,
  'airlines_outlined': Icons.airlines_outlined,
  'airplane_ticket_outlined': Icons.airplane_ticket_outlined,
  'album_outlined': Icons.album_outlined,
  'all_inbox_outlined': Icons.all_inbox_outlined,
  'all_inclusive_rounded': Icons.all_inclusive_rounded,
  'anchor_rounded': Icons.anchor_rounded,
  'animation_rounded': Icons.animation_rounded,
  'aod_outlined': Icons.aod_outlined,
  'apartment_rounded': Icons.apartment_rounded,
  'apple': Icons.apple,
  'approval_outlined': Icons.approval_outlined,
  'apps': Icons.apps,
  'architecture_rounded': Icons.architecture_rounded,
  'archive_outlined': Icons.archive_outlined,
  'art_track_rounded': Icons.art_track_rounded,
  'article_outlined': Icons.article_outlined,
  'aspect_ratio_rounded': Icons.aspect_ratio_rounded,
  'assignment_ind_outlined': Icons.assignment_ind_outlined,
  'assignment_outlined': Icons.assignment_outlined,
  'assist_walker_rounded': Icons.assist_walker_rounded,
  'assistant_photo_outlined': Icons.assistant_photo_outlined,
  'attach_file_rounded': Icons.attach_file_rounded,
  'attachment_rounded': Icons.attachment_rounded,
  'audiotrack_rounded': Icons.audiotrack_rounded,
  'auto_awesome_outlined': Icons.auto_awesome_outlined,
  'auto_fix_normal_outlined': Icons.auto_fix_normal_outlined,
  'auto_stories_outlined': Icons.auto_stories_outlined,
  'baby_changing_station_rounded': Icons.baby_changing_station_rounded,
  'back_hand_outlined': Icons.back_hand_outlined,
  'backpack_outlined': Icons.backpack_outlined,
  'backup_outlined': Icons.backup_outlined,
  'badge_outlined': Icons.badge_outlined,
  'balance_rounded': Icons.balance_rounded,
  'balcony_rounded': Icons.balcony_rounded,
  'bathtub_outlined': Icons.bathtub_outlined,
  'battery_charging_full_rounded': Icons.battery_charging_full_rounded,
  'bedtime_outlined': Icons.bedtime_outlined,
  'bento_outlined': Icons.bento_outlined,
  'biotech_rounded': Icons.biotech_rounded,
  'blender_outlined': Icons.blender_outlined,
  'blinds_rounded': Icons.blinds_rounded,
  'block': Icons.block,
  'bluetooth': Icons.bluetooth,
  'book_outlined': Icons.book_outlined,
  'bookmark_border_rounded': Icons.bookmark_border_rounded,
  'boy_rounded': Icons.boy_rounded,
  'breakfast_dining_outlined': Icons.breakfast_dining_outlined,
  'brunch_dining_rounded': Icons.brunch_dining_rounded,
  'brush': Icons.brush,
  'build': Icons.build,
  'bungalow_outlined': Icons.bungalow_outlined,
  'business_rounded': Icons.business_rounded,
  'business_center_outlined': Icons.business_center_outlined,
  'cabin_rounded': Icons.cabin_rounded,
  'cable_rounded': Icons.cable_rounded,
  'cached_rounded': Icons.cached_rounded,
  'cake_outlined': Icons.cake_outlined,
  'calculate_outlined': Icons.calculate_outlined,
  'calendar_month_outlined': Icons.calendar_month_outlined,
  'call_rounded': Icons.call_rounded,
  'camera': Icons.camera,
  'camera_alt_outlined': Icons.camera_alt_outlined,
  'campaign_outlined': Icons.campaign_outlined,
  'carpenter_outlined': Icons.carpenter_outlined,
  'casino_outlined': Icons.casino_outlined,
  'castle_outlined': Icons.castle_outlined,
  'catching_pokemon': Icons.catching_pokemon,
  'category_outlined': Icons.category_outlined,
  'celebration_outlined': Icons.celebration_outlined,
  'cell_tower_rounded': Icons.cell_tower_rounded,
  'chair_alt_rounded': Icons.chair_alt_rounded,
  'chair_outlined': Icons.chair_outlined,
  'chat_outlined': Icons.chat_outlined,
  'checkroom_rounded': Icons.checkroom_rounded,
  'child_care_rounded': Icons.child_care_rounded,
  'church_outlined': Icons.church_outlined,
  'clean_hands_outlined': Icons.clean_hands_outlined,
  'cleaning_services_outlined': Icons.cleaning_services_outlined,
  'cloud_queue_rounded': Icons.cloud_queue_rounded,
  'code': Icons.code,
  'coffee_outlined': Icons.coffee_outlined,
  'collections_outlined': Icons.collections_outlined,
  'color_lens_outlined': Icons.color_lens_outlined,
  'colorize': Icons.colorize,
  'computer_rounded': Icons.computer_rounded,
  'confirmation_number_outlined': Icons.confirmation_number_outlined,
  'construction_rounded': Icons.construction_rounded,
  'content_cut_rounded': Icons.content_cut_rounded,
  'content_paste_rounded': Icons.content_paste_rounded,
  'conveyor_belt': Icons.conveyor_belt,
  'cookie_outlined': Icons.cookie_outlined,
  'coronavirus_outlined': Icons.coronavirus_outlined,
  'corporate_fare_rounded': Icons.corporate_fare_rounded,
  'cottage_outlined': Icons.cottage_outlined,
  'countertops_outlined': Icons.countertops_outlined,
  'credit_card_rounded': Icons.credit_card_rounded,
  'crib_outlined': Icons.crib_outlined,
  'cruelty_free_outlined': Icons.cruelty_free_outlined,
  'currency_bitcoin_rounded': Icons.currency_bitcoin_rounded,
  'cyclone_rounded': Icons.cyclone_rounded,
};

List<Map<String, String>> currencies = [
  // {
  //   "ISO_Code": "AED",
  //   "Name_ID": "Dirham Uni Emirat Arab",
  //   "Symbol": "Dh",
  // },
  // {
  //   "ISO_Code": "AFN",
  //   "Name_ID": "Afghani Afghanistan",
  //   "Symbol": "؋",
  // },
  // {
  //   "ISO_Code": "ALL",
  //   "Name_ID": "Lek Albania",
  //   "Symbol": "L",
  // },
  // {
  //   "ISO_Code": "AMD",
  //   "Name_ID": "Dram Armenia",
  //   "Symbol": "֏",
  // },
  // {
  //   "ISO_Code": "ANG",
  //   "Name_ID": "Guilder Antillen Belanda",
  //   "Symbol": "ƒ",
  // },
  // {
  //   "ISO_Code": "AOA",
  //   "Name_ID": "Kwanza Angola",
  //   "Symbol": "Kz",
  // },
  // {
  //   "ISO_Code": "ARS",
  //   "Name_ID": "Peso Argentina",
  //   "Symbol": "\$",
  // },
  // {
  //   "ISO_Code": "AUD",
  //   "Name_ID": "Dolar Australia",
  //   "Symbol": "\$",
  // },
  // {
  //   "ISO_Code": "AWG",
  //   "Name_ID": "Florin Aruba",
  //   "Symbol": "ƒ",
  // },
  // {
  //   "ISO_Code": "AZN",
  //   "Name_ID": "Manat Azerbaijan",
  //   "Symbol": "₼",
  // },
  // {
  //   "ISO_Code": "BAM",
  //   "Name_ID": "Mark Bosnia dan Herzegovina",
  //   "Symbol": "KM",
  // },
  // {
  //   "ISO_Code": "BBD",
  //   "Name_ID": "Dolar Barbados",
  //   "Symbol": "\$",
  // },
  // {
  //   "ISO_Code": "BDT",
  //   "Name_ID": "Taka Bangladesh",
  //   "Symbol": "৳",
  // },
  // {
  //   "ISO_Code": "BGN",
  //   "Name_ID": "Lev Bulgaria",
  //   "Symbol": "lv.",
  // },
  // {
  //   "ISO_Code": "BHD",
  //   "Name_ID": "Dinar Bahrain",
  //   "Symbol": "BD",
  // },
  // {
  //   "ISO_Code": "BIF",
  //   "Name_ID": "Franc Burundi",
  //   "Symbol": "FBu",
  // },
  // {
  //   "ISO_Code": "BMD",
  //   "Name_ID": "Dolar Bermuda",
  //   "Symbol": "\$",
  // },
  // {
  //   "ISO_Code": "BND",
  //   "Name_ID": "Dolar Brunei",
  //   "Symbol": "\$",
  // },
  // {
  //   "ISO_Code": "BOB",
  //   "Name_ID": "Boliviano Bolivia",
  //   "Symbol": "Bs",
  // },
  // {
  //   "ISO_Code": "BRL",
  //   "Name_ID": "Real Brasil",
  //   "Symbol": "R\$",
  // },
  // {
  //   "ISO_Code": "BSD",
  //   "Name_ID": "Dolar Bahama",
  //   "Symbol": "\$",
  // },
  // {
  //   "ISO_Code": "BTN",
  //   "Name_ID": "Ngultrum Bhutan",
  //   "Symbol": "Nu",
  // },
  // {
  //   "ISO_Code": "BWP",
  //   "Name_ID": "Pula Botswana",
  //   "Symbol": "P",
  // },
  // {
  //   "ISO_Code": "BYN",
  //   "Name_ID": "Rubel Belarusia",
  //   "Symbol": "Br",
  // },
  // {
  //   "ISO_Code": "BZD",
  //   "Name_ID": "Dolar Belize",
  //   "Symbol": "\$",
  // },
  // {
  //   "ISO_Code": "CAD",
  //   "Name_ID": "Dolar Kanada",
  //   "Symbol": "\$",
  // },
  // {
  //   "ISO_Code": "CDF",
  //   "Name_ID": "Franc Kongo",
  //   "Symbol": "FC",
  // },
  // {
  //   "ISO_Code": "CHF",
  //   "Name_ID": "Franc Swiss",
  //   "Symbol": "Fr",
  // },
  // {
  //   "ISO_Code": "CLP",
  //   "Name_ID": "Peso Chili",
  //   "Symbol": "\$",
  // },
  // {
  //   "ISO_Code": "CNY",
  //   "Name_ID": "Renminbi",
  //   "Symbol": "¥",
  // },
  // {
  //   "ISO_Code": "COP",
  //   "Name_ID": "Peso Kolombia",
  //   "Symbol": "\$",
  // },
  // {
  //   "ISO_Code": "CRC",
  //   "Name_ID": "Colón Kosta Rika",
  //   "Symbol": "₡",
  // },
  // {
  //   "ISO_Code": "CUP",
  //   "Name_ID": "Peso Kuba",
  //   "Symbol": "\$",
  // },
  // {
  //   "ISO_Code": "CVE",
  //   "Name_ID": "Escudo Tanjung Verde",
  //   "Symbol": "\$",
  // },
  // {
  //   "ISO_Code": "CZK",
  //   "Name_ID": "Koruna Ceko",
  //   "Symbol": "Kč",
  // },
  // {
  //   "ISO_Code": "DJF",
  //   "Name_ID": "Franc Djibouti",
  //   "Symbol": "Fdj",
  // },
  // {
  //   "ISO_Code": "DKK",
  //   "Name_ID": "Krone Denmark",
  //   "Symbol": "kr",
  // },
  // {
  //   "ISO_Code": "DOP",
  //   "Name_ID": "Peso Dominika",
  //   "Symbol": "\$",
  // },
  // {
  //   "ISO_Code": "DZD",
  //   "Name_ID": "Dinar Algeria",
  //   "Symbol": "DA",
  // },
  // {
  //   "ISO_Code": "EGP",
  //   "Name_ID": "Pound Mesir",
  //   "Symbol": "LE",
  // },
  // {
  //   "ISO_Code": "ETB",
  //   "Name_ID": "Birr Ethiopia",
  //   "Symbol": "Br",
  // },
  // {
  //   "ISO_Code": "EUR",
  //   "Name_ID": "Euro",
  //   "Symbol": "€",
  // },
  // {
  //   "ISO_Code": "FJD",
  //   "Name_ID": "Dolar Fiji",
  //   "Symbol": "\$",
  // },
  // {
  //   "ISO_Code": "GBP",
  //   "Name_ID": "Sterling",
  //   "Symbol": "£",
  // },
  // {
  //   "ISO_Code": "GEL",
  //   "Name_ID": "Lari Georgia",
  //   "Symbol": "₾",
  // },
  // {
  //   "ISO_Code": "GHS",
  //   "Name_ID": "Cedi Ghana",
  //   "Symbol": "₵",
  // },
  // {
  //   "ISO_Code": "GMD",
  //   "Name_ID": "Dalasi Gambia",
  //   "Symbol": "D",
  // },
  // {
  //   "ISO_Code": "GNF",
  //   "Name_ID": "Franc Guinea",
  //   "Symbol": "Fr",
  // },
  // {
  //   "ISO_Code": "GTQ",
  //   "Name_ID": "Quetzal Guatemala",
  //   "Symbol": "Q",
  // },
  // {
  //   "ISO_Code": "GYD",
  //   "Name_ID": "Dolar Guyana",
  //   "Symbol": "\$",
  // },
  // {
  //   "ISO_Code": "HKD",
  //   "Name_ID": "Dolar Hong Kong",
  //   "Symbol": "\$",
  // },
  // {
  //   "ISO_Code": "HNL",
  //   "Name_ID": "Lempira Honduras",
  //   "Symbol": "L",
  // },
  // {
  //   "ISO_Code": "HTG",
  //   "Name_ID": "Gourde Haiti",
  //   "Symbol": "G",
  // },
  // {
  //   "ISO_Code": "HUF",
  //   "Name_ID": "Forint Hungaria",
  //   "Symbol": "Ft",
  // },
  {
    "ISO_Code": "IDR",
    "Name_ID": "Rupiah Indonesia",
    "Symbol": "Rp",
  },
  // {
  //   "ISO_Code": "ILS",
  //   "Name_ID": "Shekel Israel",
  //   "Symbol": "₪",
  // },
  // {
  //   "ISO_Code": "INR",
  //   "Name_ID": "Rupee India",
  //   "Symbol": "₹",
  // },
  // {
  //   "ISO_Code": "IQD",
  //   "Name_ID": "Dinar Irak",
  //   "Symbol": "ID",
  // },
  // {
  //   "ISO_Code": "IRR",
  //   "Name_ID": "Rial Iran",
  //   "Symbol": "Rl",
  // },
  // {
  //   "ISO_Code": "ISK",
  //   "Name_ID": "Króna Islandia",
  //   "Symbol": "kr",
  // },
  // {
  //   "ISO_Code": "JMD",
  //   "Name_ID": "Dolar Jamaika",
  //   "Symbol": "\$",
  // },
  // {
  //   "ISO_Code": "JOD",
  //   "Name_ID": "Dinar Yordania",
  //   "Symbol": "JD",
  // },
  // {
  //   "ISO_Code": "JPY",
  //   "Name_ID": "Yen Jepang",
  //   "Symbol": "¥",
  // },
  // {
  //   "ISO_Code": "KES",
  //   "Name_ID": "Shilling Kenya",
  //   "Symbol": "Sh",
  // },
  // {
  //   "ISO_Code": "KGS",
  //   "Name_ID": "Som Kirgizstan",
  //   "Symbol": "⃀",
  // },
  // {
  //   "ISO_Code": "KHR",
  //   "Name_ID": "Riel Kamboja",
  //   "Symbol": "៛",
  // },
  // {
  //   "ISO_Code": "KMF",
  //   "Name_ID": "Franc Komoro",
  //   "Symbol": "FC",
  // },
  // {
  //   "ISO_Code": "KRW",
  //   "Name_ID": "Won Korea Selatan",
  //   "Symbol": "₩",
  // },
  // {
  //   "ISO_Code": "KWD",
  //   "Name_ID": "Dinar Kuwait",
  //   "Symbol": "KD",
  // },
  // {
  //   "ISO_Code": "KYD",
  //   "Name_ID": "Dolar Kepulauan Cayman",
  //   "Symbol": "\$",
  // },
  // {
  //   "ISO_Code": "KZT",
  //   "Name_ID": "	Tenge Kazakhstan",
  //   "Symbol": "₸",
  // },
  // {
  //   "ISO_Code": "LAK",
  //   "Name_ID": "Kip Laos",
  //   "Symbol": "₭",
  // },
  // {
  //   "ISO_Code": "LBP",
  //   "Name_ID": "Pound Lebanon",
  //   "Symbol": "LL",
  // },
  // {
  //   "ISO_Code": "LKR",
  //   "Name_ID": "Rupee Sri Lanka",
  //   "Symbol": "Re",
  // },
  // {
  //   "ISO_Code": "LRD",
  //   "Name_ID": "Dolar Liberia",
  //   "Symbol": "\$",
  // },
  // {
  //   "ISO_Code": "LSL",
  //   "Name_ID": "Loti Lesotho",
  //   "Symbol": "L",
  // },
  // {
  //   "ISO_Code": "LYD",
  //   "Name_ID": "Dinar Libya",
  //   "Symbol": "LD",
  // },
  // {
  //   "ISO_Code": "MAD",
  //   "Name_ID": "Dirham Maroko",
  //   "Symbol": "DH",
  // },
  // {
  //   "ISO_Code": "MDL",
  //   "Name_ID": "Leu Moldova",
  //   "Symbol": "Leu",
  // },
  // {
  //   "ISO_Code": "MGA",
  //   "Name_ID": "Ariary Madagaskar",
  //   "Symbol": "Ar",
  // },
  // {
  //   "ISO_Code": "MKD",
  //   "Name_ID": "Denar Makedonia",
  //   "Symbol": "DEN",
  // },
  // {
  //   "ISO_Code": "MMK",
  //   "Name_ID": "Kyat Burma",
  //   "Symbol": "K",
  // },
  // {
  //   "ISO_Code": "MOP",
  //   "Name_ID": "Pataca Makau",
  //   "Symbol": "\$",
  // },
  // {
  //   "ISO_Code": "MRY",
  //   "Name_ID": "Ringgit Malaysia",
  //   "Symbol": "RM",
  // },
  // {
  //   "ISO_Code": "MUR",
  //   "Name_ID": "Rupee Mauritania",
  //   "Symbol": "Re",
  // },
  // {
  //   "ISO_Code": "MVR",
  //   "Name_ID": "Rufiyaa Maladewa",
  //   "Symbol": "Rf",
  // },
  // {
  //   "ISO_Code": "MWK",
  //   "Name_ID": "Kwacha Malawi",
  //   "Symbol": "K",
  // },
  // {
  //   "ISO_Code": "MXN",
  //   "Name_ID": "Peso Meksiko",
  //   "Symbol": "\$",
  // },
  // {
  //   "ISO_Code": "MZN",
  //   "Name_ID": "Metical Mozambik",
  //   "Symbol": "Mt",
  // },
  // {
  //   "ISO_Code": "NAD",
  //   "Name_ID": "Dolar Namibia",
  //   "Symbol": "\$",
  // },
  // {
  //   "ISO_Code": "NGN",
  //   "Name_ID": "Naira Nigeria",
  //   "Symbol": "₦",
  // },
  // {
  //   "ISO_Code": "NIO",
  //   "Name_ID": "Córdoba Nicaragua",
  //   "Symbol": "C\$",
  // },
  // {
  //   "ISO_Code": "NOK",
  //   "Name_ID": "Krone Norwegia",
  //   "Symbol": "kr",
  // },
  // {
  //   "ISO_Code": "NPR",
  //   "Name_ID": "Rupee Nepal",
  //   "Symbol": "Re",
  // },
  // {
  //   "ISO_Code": "NZD",
  //   "Name_ID": "Dolar Selandia Baru",
  //   "Symbol": "\$",
  // },
  // {
  //   "ISO_Code": "OMR",
  //   "Name_ID": "Rial Oman",
  //   "Symbol": "RO",
  // },
  // {
  //   "ISO_Code": "PAB",
  //   "Name_ID": "Balboa Panama",
  //   "Symbol": "B/",
  // },
  // {
  //   "ISO_Code": "PEN",
  //   "Name_ID": "Sol Peru",
  //   "Symbol": "S/",
  // },
  // {
  //   "ISO_Code": "PGK",
  //   "Name_ID": "Kina Papua Nugini",
  //   "Symbol": "K",
  // },
  // {
  //   "ISO_Code": "PHP",
  //   "Name_ID": "Peso Filipina",
  //   "Symbol": "₱",
  // },
  // {
  //   "ISO_Code": "PKR",
  //   "Name_ID": "Rupee Pakistan",
  //   "Symbol": "Re",
  // },
  // {
  //   "ISO_Code": "PLN",
  //   "Name_ID": "Złoty Polandia",
  //   "Symbol": "zł",
  // },
  // {
  //   "ISO_Code": "PYG",
  //   "Name_ID": "Guaraní Paraguay",
  //   "Symbol": "₲",
  // },
  // {
  //   "ISO_Code": "QAR",
  //   "Name_ID": "Riyal Qatar",
  //   "Symbol": "QR",
  // },
  // {
  //   "ISO_Code": "RON",
  //   "Name_ID": "Leu Romania",
  //   "Symbol": "Leu",
  // },
  // {
  //   "ISO_Code": "RSD",
  //   "Name_ID": "Dinar Serbia",
  //   "Symbol": "DIN",
  // },
  // {
  //   "ISO_Code": "RUB",
  //   "Name_ID": "Rubel Rusia",
  //   "Symbol": "₽",
  // },
  // {
  //   "ISO_Code": "RWF",
  //   "Name_ID": "Franc Rwanda",
  //   "Symbol": "FRw",
  // },
  // {
  //   "ISO_Code": "SAR",
  //   "Name_ID": "Riyal Saudi",
  //   "Symbol": "Rl",
  // },
  // {
  //   "ISO_Code": "SBD",
  //   "Name_ID": "Dolar Kepulauan Solomon",
  //   "Symbol": "\$",
  // },
  // {
  //   "ISO_Code": "SCR",
  //   "Name_ID": "Rupee Seychelles",
  //   "Symbol": "Re",
  // },
  // {
  //   "ISO_Code": "SDG",
  //   "Name_ID": "Pound Sudan",
  //   "Symbol": "LS",
  // },
  // {
  //   "ISO_Code": "SEK",
  //   "Name_ID": "Krona Swedia",
  //   "Symbol": "kr",
  // },
  // {
  //   "ISO_Code": "SGD",
  //   "Name_ID": "Dolar Singapura",
  //   "Symbol": "\$",
  // },
  // {
  //   "ISO_Code": "SHP",
  //   "Name_ID": "Pound Saint Helena",
  //   "Symbol": "£",
  // },
  // {
  //   "ISO_Code": "SOS",
  //   "Name_ID": "Shilling Somalia",
  //   "Symbol": "Sh",
  // },
  // {
  //   "ISO_Code": "SRD",
  //   "Name_ID": "Dolar Suriname",
  //   "Symbol": "\$",
  // },
  // {
  //   "ISO_Code": "SZL",
  //   "Name_ID": "Lilangeni Eswatini",
  //   "Symbol": "L",
  // },
  // {
  //   "ISO_Code": "THB",
  //   "Name_ID": "Baht Thailand",
  //   "Symbol": "฿	",
  // },
  // {
  //   "ISO_Code": "TJS",
  //   "Name_ID": "Somoni Tajikistan",
  //   "Symbol": "SM",
  // },
  // {
  //   "ISO_Code": "TMT",
  //   "Name_ID": "Manat Turkmenistan",
  //   "Symbol": "m",
  // },
  // {
  //   "ISO_Code": "TND",
  //   "Name_ID": "Dinar Tunisia",
  //   "Symbol": "DT",
  // },
  // {
  //   "ISO_Code": "TOP",
  //   "Name_ID": "Pa'anga Tonga",
  //   "Symbol": "T\$",
  // },
  // {
  //   "ISO_Code": "TRY",
  //   "Name_ID": "Lira Turki",
  //   "Symbol": "₺",
  // },
  // {
  //   "ISO_Code": "TTD",
  //   "Name_ID": "Dolar Trinidad dan Tobago",
  //   "Symbol": "\$",
  // },
  // {
  //   "ISO_Code": "TWD",
  //   "Name_ID": "Dolar Taiwan Baru",
  //   "Symbol": "\$",
  // },
  // {
  //   "ISO_Code": "TZS",
  //   "Name_ID": "Shilling Tanzania",
  //   "Symbol": "Sh",
  // },
  // {
  //   "ISO_Code": "UAH",
  //   "Name_ID": "Hryvnia Ukraina",
  //   "Symbol": "₴",
  // },
  // {
  //   "ISO_Code": "UGX",
  //   "Name_ID": "Shilling Uganda",
  //   "Symbol": "Sh",
  // },
  {
    "ISO_Code": "USD",
    "Name_ID": "Dolar Amerika Serikat",
    "Symbol": "\$",
  },
  // {
  //   "ISO_Code": "UYU",
  //   "Name_ID": "Peso Uruguay",
  //   "Symbol": "\$",
  // },
  // {
  //   "ISO_Code": "UZS",
  //   "Name_ID": "So'm Uzbekistan",
  //   "Symbol": "лв",
  // },
  // {
  //   "ISO_Code": "VND",
  //   "Name_ID": "Đồng Vietnam",
  //   "Symbol": "₫",
  // },
  // {
  //   "ISO_Code": "XAF",
  //   "Name_ID": "Franc CFA Afrika Tengah",
  //   "Symbol": "F.CFA",
  // },
  // {
  //   "ISO_Code": "XCD",
  //   "Name_ID": "Dolar Karibia Timur",
  //   "Symbol": "EC\$",
  // },
  // {
  //   "ISO_Code": "XOF",
  //   "Name_ID": "Frank CFA Afrika Barat",
  //   "Symbol": "F.CFA",
  // },
  // {
  //   "ISO_Code": "XPF",
  //   "Name_ID": "Franc CFP",
  //   "Symbol": "₣",
  // },
  // {
  //   "ISO_Code": "YER",
  //   "Name_ID": "Rial Yaman",
  //   "Symbol": "Rl",
  // },
  // {
  //   "ISO_Code": "ZAR",
  //   "Name_ID": "Rand Afrika Selatan",
  //   "Symbol": "R",
  // },
  // {
  //   "ISO_Code": "ZMW",
  //   "Name_ID": "Kwacha Zambia",
  //   "Symbol": "K",
  // },
  // {
  //   "ISO_Code": "ZWL",
  //   "Name_ID": "Dolar Zimbabwe",
  //   "Symbol": "\$",
  // },
];