// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSwUGegB5X9ecGgGiqNMmORArVk5YKXAY',
    appId: '1:707991192150:web:0f8cf80f1da847e18871f7',
    messagingSenderId: '707991192150',
    projectId: 'learn-b46a8',
    authDomain: 'learn-b46a8.firebaseapp.com',
    storageBucket: 'learn-b46a8.appspot.com',
    measurementId: 'G-68FWKYM001',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQfEdM5LoKJPyeeUl0YFVPLj7SpGtQZV0',
    appId: '1:707991192150:android:ce9231549a9fdc978871f7',
    messagingSenderId: '707991192150',
    projectId: 'learn-b46a8',
    storageBucket: 'learn-b46a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEBTR_YplwWxsqOi5wKTp2iTe49yAy2U0',
    appId: '1:707991192150:ios:56b29d2e63c3892e8871f7',
    messagingSenderId: '707991192150',
    projectId: 'learn-b46a8',
    storageBucket: 'learn-b46a8.appspot.com',
    iosClientId: '707991192150-pc9q29f5t4lo9n0uag0on5n277qtei1p.apps.googleusercontent.com',
    iosBundleId: 'com.exinflow.exinflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEBTR_YplwWxsqOi5wKTp2iTe49yAy2U0',
    appId: '1:707991192150:ios:56b29d2e63c3892e8871f7',
    messagingSenderId: '707991192150',
    projectId: 'learn-b46a8',
    storageBucket: 'learn-b46a8.appspot.com',
    iosClientId: '707991192150-pc9q29f5t4lo9n0uag0on5n277qtei1p.apps.googleusercontent.com',
    iosBundleId: 'com.exinflow.exinflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSwUGegB5X9ecGgGiqNMmORArVk5YKXAY',
    appId: '1:707991192150:web:0f8cf80f1da847e18871f7',
    messagingSenderId: '707991192150',
    projectId: 'learn-b46a8',
    authDomain: 'learn-b46a8.firebaseapp.com',
    storageBucket: 'learn-b46a8.appspot.com',
    measurementId: 'G-68FWKYM001',
  );
}
